name: Deploy Project 1 to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known_hosts
        run: ssh-keyscan -H 174.138.17.127 >> ~/.ssh/known_hosts

      - name: Sync Project 1 to Droplet
        run: |
          rsync -az --delete \
            --exclude=node_modules \
            --exclude=.git \
            ./ root@174.138.17.127:/var/www/term-ez/backend-api
      - name: Create .env file on Droplet
        run: |
          ssh root@174.138.17.127 << EOF
            cd /var/www/term-ez/backend-api
            cat > .env << EOL
            NODE_ENV=production
            API_TOP_UP_URL=${{ secrets.API_TOP_UP_URL }}
            MONGO_URI=${{ secrets.MONGO_URI }}
            CALLBACK_SECRET_KEY=${{ secrets.CALLBACK_SECRET_KEY }}
            INDENTIFY=${{ secrets.INDENTIFY }}
            PASSWORD=${{ secrets.PASSWORD }}
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            PUBNUB_SUBSCRIBE_KEY=${{ secrets.PUBNUB_SUBSCRIBE_KEY }}
            PUBNUB_PUBLISH_KEY=${{ secrets.PUBNUB_PUBLISH_KEY }}
            PUBNUB_SECRET_KEY=${{ secrets.PUBNUB_SECRET_KEY }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            EOL
          EOF

      - name: Restart Project 1 Container
        run: |
          ssh root@174.138.17.127 << 'EOF'
            cd /var/www/term-ez/backend-api
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
          EOF
